### ISSUE TITLE
use https://github.com/derhuerst/vbb-client instead of transport.rest

### ISSUE THREAD

**Issue by jfilter** [jfilter/brandengo#2]

**Comment by jfilter** [comment]
no reason for now.

**Comment by derhuerst** [comment]
note that `transport.rest` is shut off. you would have to query `vbb.transport.rest`.

**Comment by derhuerst** [comment]
FYI this issue is still relevant, as BrandenGo appears to be working but doesn't.

**Comment by jfilter** [comment]
I am currently on holiday but will fix it as soon as I have time.
